create table stock_hist(
    id serial primary key,
    symbol char(6),
    trade_date date,
    open float,
    close float,
    high float,
    low float,
    volume int,
    turnover float,
    amplitude float,
    change_percent float,
    change float,
    turnover_rate float,
    ma5 float,
    ma13 float,
    ma21 float,
    ma34 float,
    ma55 float,
    ma89 float,
    ma144 float,
    ma233 float,
    czsczb int
)